### ISSUE TITLE
Name change doesn't allow you to keep a VoidChest

### ISSUE THREAD

**Issue by refracc** [Shin1gamiX/VoidChest#6]
**Bug Description**
When you change your account name, you lose access to all your voidchests.

**To Reproduce**
Change your name
Log back in
You can't change a thing with your void chests

**Expected behavior**
Should have UUID support instead of names. Still have the player name showing on the voidchest hologram; but have the chests working with UUIDs.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Shin1gamiX** [comment]
VoidChest was originally made to work with usernames rather than uuids so as to allow support for cracked servers where UUID has an unexpected behavior. VoidChest currently stores data on a player's username rather than UUID. 

If your server is running in offline mode, I suggest you kept things as they are currently and keep voidchest to storing things in usernames rather than UUIDs. 

If your server is running in online mode, I highly doubt users are going to be changing their username every 1 month (since changing their name puts them in a 1 month cooldown till they can re do it).

However, if that is something you still want to change, I'd be more than happy to discuss this over discord texts.

I greatly appreciate you create this issue here and communicating with me.
